name: Validate and Build Registry

# give the GITHUB_TOKEN permission to push commits
permissions:
  contents: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # ensure the token is available for pushes
          persist-credentials: true
          # fetch full history so we can push back
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Validate Entries
        run: npm run validate

  build:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # ensure the token is available for pushes
          persist-credentials: true
          # fetch full history so we can push back
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build Index
        run: npm run build

      - name: Commit dist/index.json back to gh-pages
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: update dist/index.json'
          branch: gh-pages
          file_pattern: dist/index.json