name: Validate and Build Registry

# give the GITHUB_TOKEN permission to push commits
permissions:
  contents: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Validate Entries
        run: npm run validate

  build:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Remove untracked files before checkout
        run: git clean -fdx

      - name: Install Dependencies
        run: npm install

      - name: Build Index
        run: npm run build

      - name: Copy dist folder to temp
        run: cp -r dist /tmp/dist

      - name: Remove all files from dist before switching branch
        run: rm -rf dist/*

      - name: Checkout gh-pages branch
        run: |
          git fetch origin gh-pages:gh-pages
          git checkout gh-pages

      - name: Copy built dist folder from temp
        run: cp -r /tmp/dist/* dist/

      - name: List dist contents
        run: ls -l dist

      - name: Show git status
        run: git status

      - name: Show git diff
        run: git diff dist/

      - name: Add dist files to git
        run: git add dist/*

      - name: Commit dist back to gh-pages
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: update dist'
          branch: gh-pages
          file_pattern: dist/*
          file_pattern: dist/index.json