name: Validate and Build Registry

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm install
      - name: Validate Entries
        run: npm run validate

  build:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm install
      - name: Build Index
        run: npm run build
      - name: Commit dist/index.json back to main
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: update dist/index.json'
          branch: main
          file_pattern: dist/index.json
          add_untracked_files: true